# -*- coding: utf-8 -*-
"""MyInfo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RKGxY3_rpg2LdMGfeEZeS3HCPoFXSss
"""

# CS175-50
#Louis Keller

print("Louis Keller" )
print("MS in Data Science")
